
title: Documentation
description: >- # this means to ignore newlines until "baseurl:"
  When reviewing a PR for this repo, you can see what the documentation,
  e.g. the storybook, will look like when published for the branches
  named above.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com

# Build settings
theme: minima
plugins:
  - jekyll-feed

collections:
  branches:
    output: true
    permalink: /branches/:path/

repo_name: "TBD"


repo: ucsb-cs156-s25/team01-s25-06
owner: ucsb-cs156-s25
repo_name: team01-s25-06
pull_requests: [{"author":{"id":"MDQ6VXNlcjU2NDU3OTc1","is_bot":false,"login":"RiyaGupta1234","name":"Riya Gupta"},"headRefName":"riya-delete-for-helprequest-table","number":48,"title":"Riya delete for helprequest table","url":"https://github.com/ucsb-cs156-s25/team01-s25-06/pull/48"},{"author":{"id":"MDQ6VXNlcjU2NDU3OTc1","is_bot":false,"login":"RiyaGupta1234","name":"Riya Gupta"},"headRefName":"riya-put-for-helprequest-table","number":47,"title":"Riya put for helprequest table","url":"https://github.com/ucsb-cs156-s25/team01-s25-06/pull/47"},{"author":{"id":"MDQ6VXNlcjU2NDU3OTc1","is_bot":false,"login":"RiyaGupta1234","name":"Riya Gupta"},"headRefName":"riya-helpreq-get-by-id","number":46,"title":"riya - add get by id for help requests","url":"https://github.com/ucsb-cs156-s25/team01-s25-06/pull/46"},{"author":{"id":"MDQ6VXNlcjU2NDU3OTc1","is_bot":false,"login":"RiyaGupta1234","name":"Riya Gupta"},"headRefName":"riya-create-helpreq-controller","number":44,"title":"riya - create helpreq controller, add GET /all and POST methods","url":"https://github.com/ucsb-cs156-s25/team01-s25-06/pull/44"}]
