
title: Documentation
description: >- # this means to ignore newlines until "baseurl:"
  When reviewing a PR for this repo, you can see what the documentation,
  e.g. the storybook, will look like when published for the branches
  named above.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com

# Build settings
theme: minima
plugins:
  - jekyll-feed

collections:
  branches:
    output: true
    permalink: /branches/:path/

repo_name: "TBD"


repo: ucsb-cs156-s25/team01-s25-06
owner: ucsb-cs156-s25
repo_name: team01-s25-06
pull_requests: [{"author":{"id":"MDQ6VXNlcjM1MTE2OTc0","is_bot":false,"login":"sanjana-jilla-913","name":"Sanjana Jilla"},"headRefName":"sj-create-article-controller","number":55,"title":"sj - Added the article controller and set up add, get, and post methods","url":"https://github.com/ucsb-cs156-s25/team01-s25-06/pull/55"},{"author":{"id":"U_kgDOCWXRgw","is_bot":false,"login":"timothy878","name":""},"headRefName":"Timothy-UCSBOrganizations-get-by-id","number":53,"title":"Timothy - add get by id for UCSB Organizations ","url":"https://github.com/ucsb-cs156-s25/team01-s25-06/pull/53"},{"author":{"id":"MDQ6VXNlcjY2ODQ5Nzc3","is_bot":false,"login":"yarwinliu","name":""},"headRefName":"yl-commit-create-db","number":52,"title":"yl - create database table for MenuItemReviews","url":"https://github.com/ucsb-cs156-s25/team01-s25-06/pull/52"},{"author":{"id":"U_kgDOCWXRgw","is_bot":false,"login":"timothy878","name":""},"headRefName":"Timothy-UCSBOrganizationsController","number":50,"title":"Created UCSBOrganizations Controller! add Get /all and Post message","url":"https://github.com/ucsb-cs156-s25/team01-s25-06/pull/50"},{"author":{"id":"MDQ6VXNlcjU2NDU3OTc1","is_bot":false,"login":"RiyaGupta1234","name":"Riya Gupta"},"headRefName":"riya-delete-for-helprequest-table","number":48,"title":"Riya delete for helprequest table","url":"https://github.com/ucsb-cs156-s25/team01-s25-06/pull/48"},{"author":{"id":"MDQ6VXNlcjU2NDU3OTc1","is_bot":false,"login":"RiyaGupta1234","name":"Riya Gupta"},"headRefName":"riya-put-for-helprequest-table","number":47,"title":"Riya put for helprequest table","url":"https://github.com/ucsb-cs156-s25/team01-s25-06/pull/47"},{"author":{"id":"MDQ6VXNlcjU2NDU3OTc1","is_bot":false,"login":"RiyaGupta1234","name":"Riya Gupta"},"headRefName":"riya-helpreq-get-by-id","number":46,"title":"riya - add get by id for help requests","url":"https://github.com/ucsb-cs156-s25/team01-s25-06/pull/46"}]
