
title: Documentation
description: >- # this means to ignore newlines until "baseurl:"
  When reviewing a PR for this repo, you can see what the documentation,
  e.g. the storybook, will look like when published for the branches
  named above.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com

# Build settings
theme: minima
plugins:
  - jekyll-feed

collections:
  branches:
    output: true
    permalink: /branches/:path/

repo_name: "TBD"


repo: ucsb-cs156-s25/team01-s25-06
owner: ucsb-cs156-s25
repo_name: team01-s25-06
pull_requests: [{"author":{"id":"MDQ6VXNlcjY2ODQ5Nzc3","is_bot":false,"login":"yarwinliu","name":""},"headRefName":"yl-mir-put-table","number":66,"title":"Yl mir put table","url":"https://github.com/ucsb-cs156-s25/team01-s25-06/pull/66"},{"author":{"id":"MDQ6VXNlcjM1MTE2OTc0","is_bot":false,"login":"sanjana-jilla-913","name":"Sanjana Jilla"},"headRefName":"sj-articles-delete","number":65,"title":"Sj articles delete","url":"https://github.com/ucsb-cs156-s25/team01-s25-06/pull/65"},{"author":{"id":"U_kgDOBXu1PQ","is_bot":false,"login":"aryanchopra1802","name":""},"headRefName":"revert-54-Aryan-ReqRequestTable","number":56,"title":"Revert \"Aryan req request table\"","url":"https://github.com/ucsb-cs156-s25/team01-s25-06/pull/56"}]
