
title: Documentation
description: >- # this means to ignore newlines until "baseurl:"
  When reviewing a PR for this repo, you can see what the documentation,
  e.g. the storybook, will look like when published for the branches
  named above.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com

# Build settings
theme: minima
plugins:
  - jekyll-feed

collections:
  branches:
    output: true
    permalink: /branches/:path/

repo_name: "TBD"


repo: ucsb-cs156-s25/team01-s25-06
owner: ucsb-cs156-s25
repo_name: team01-s25-06
pull_requests: [{"author":{"id":"U_kgDOBXu1PQ","is_bot":false,"login":"aryanchopra1802","name":""},"headRefName":"aryanchopra-RecReq-getbyID","number":61,"title":"aryanchopra- Completed step 4; added PUT method and I believe it pass…","url":"https://github.com/ucsb-cs156-s25/team01-s25-06/pull/61"},{"author":{"id":"U_kgDOCWXRgw","is_bot":false,"login":"timothy878","name":""},"headRefName":"Timothy-delete-for-UCSBOrganizations","number":59,"title":"Timothy - delete for ucsb organizations","url":"https://github.com/ucsb-cs156-s25/team01-s25-06/pull/59"},{"author":{"id":"U_kgDOBXu1PQ","is_bot":false,"login":"aryanchopra1802","name":""},"headRefName":"revert-54-Aryan-ReqRequestTable","number":56,"title":"Revert \"Aryan req request table\"","url":"https://github.com/ucsb-cs156-s25/team01-s25-06/pull/56"},{"author":{"id":"MDQ6VXNlcjU2NDU3OTc1","is_bot":false,"login":"RiyaGupta1234","name":"Riya Gupta"},"headRefName":"riya-delete-for-helprequest-table","number":48,"title":"Riya delete for helprequest table","url":"https://github.com/ucsb-cs156-s25/team01-s25-06/pull/48"}]
